export const FacebookLink = ""
export const InstagramLink = ""
export const YouTubeLink = ""
export const SchoolGoogleLocationLink = ""
export const SchoolPhoneLink = "tel:8447695298"
export const SchoolEmailLink = "mailto:sakurapreschool.kok@gmail.com"
